Repository konkuk-galaxy/frontend, pull requests merged in 2023-05, with the labels that each got.

#11 feat: 엔딩 화면 구현
  end.css
  end.html
  galaxy.css
  game.js
  stars-g5d44ea9a5_1920.jpg
Labels: 🔭 스코어 및 엔딩 구현 🔭

#10 #5 벽돌배치
  dummy.md
  game ver.commit 1.js
  img/bricks.jpg
  level1.html
Labels: 👁 인터페이스 및 디자인 👁

#18 스토리 스킵 버튼 위치를 변경한다
  story.html
Labels: 🧩 리팩터링 🧩, 👁 인터페이스 및 디자인 👁

#25 Feat/game logic
  game ver.commit 2.js
  game ver.commit 3.js
  image.zip
  img/free-icon-snail-2675426.png
  level1.html
  level2.html
  level3.html
Labels: 💥 기믹 요소 구현 💥

#33 feat: 점수 계산 함수 구현
  game ver.commit 1.js
  game ver.commit 3.js
  game.js
  start.js
Labels: 🔭 스코어 및 엔딩 구현 🔭

#43 feat: 승패 여부에 따른 결과 반환
  end.html
  end.js
  game ver.commit 3.js
  game.js
  setting.js
Labels: 🔭 스코어 및 엔딩 구현 🔭

#44 feat: 난이도 조절, 게임종료 선택창 제거 및 자원점수 변경
  end.html
  game ver.commit 3.js
  level2.html
  level3.html
Labels: 🎲 난이도 설정 🎲

#51 블록 안쪽 판정 구현, 공 과속 방지
  game ver.commit 3.js
Labels: ❗️사소한 버그 수정❗️

#54 hotfix: 스테이지 매우 크게 변경되는 버그 수정
  game.js
Labels: ❗️사소한 버그 수정❗️
